// lib/auth/session.ts
//
// The ONE auth resolver (architecture §0.1, ownership-map). Resolves:
//   Supabase user (auth.uid) → employees row → employee_roles
// into a single `AuthUser`. No `getAuthContext`/`getCurrentEmployee` duplicates exist.
//
// Keyless / DEMO contract: if Supabase is NOT configured, or DEMO_MODE is on and there
// is no real session, we return a synthetic in-memory demo AuthUser and DO NOT touch
// the DB — so every view renders keyless. Once real keys + a session exist, the real
// employee/roles are resolved with RLS.

import { isConfigured } from '@/lib/config/env';
import { isDemoMode } from '@/lib/config/flags';
import { appTable, createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import type { AppRole, AuthUser } from '@/lib/types';

/** The synthetic demo identity used for keyless boot (no DB, no session). */
const DEMO_USER: AuthUser = {
  userId: 'demo-user',
  employeeId: 'demo-employee',
  functionId: 'demo-function',
  displayName: 'Demo User',
  email: null,
  // In the single-user demo the user holds every role so all chrome is reachable.
  roles: ['developer', 'manager', 'function_lead', 'admin'],
  isDemo: true,
};

/** Return a copy of the demo user (so callers can't mutate the shared object). */
export function demoUser(): AuthUser {
  return { ...DEMO_USER, roles: [...DEMO_USER.roles] };
}

/**
 * The demo identity bound to the REAL `is_demo` "self" employee row (created by the
 * pipeline/onboarding), so the demo session keys off the actual scored data (My view,
 * function aggregates, connector status) instead of the synthetic placeholder ids.
 * Uses the service-role client because the is_demo row has no `user_id` (RLS can't
 * resolve it without a session). Falls back to the synthetic demo user if Supabase is
 * unavailable or no self employee exists yet (keyless boot stays safe).
 */
async function demoUserFromDb(): Promise<AuthUser> {
  if (!isConfigured('supabase')) return demoUser();
  try {
    const admin = createAdminClient() as unknown as {
      from: (t: string) => {
        select: (c: string) => {
          eq: (
            k: string,
            v: unknown,
          ) => {
            limit: (n: number) => { maybeSingle: () => Promise<{ data: Record<string, unknown> | null }> };
          };
        };
      };
    };
    const { data } = await admin
      .from('employees')
      .select('id, function_id, name, email')
      .eq('is_demo', true)
      .limit(1)
      .maybeSingle();
    if (!data) return demoUser();
    return {
      userId: 'demo-user',
      employeeId: data.id as string,
      functionId: data.function_id as string,
      displayName: (data.name as string | null) ?? 'You',
      email: (data.email as string | null) ?? null,
      roles: ['developer', 'manager', 'function_lead', 'admin'],
      isDemo: true,
    };
  } catch {
    return demoUser();
  }
}

/**
 * Resolve the current AuthUser, or null when unauthenticated (and not in a demo
 * fallback). Never throws on a missing key — returns the demo user instead so views
 * render keyless.
 */
export async function getAuthUser(): Promise<AuthUser | null> {
  // Keyless boot: no Supabase → demo context (if DEMO_MODE) else unauthenticated.
  if (!isConfigured('supabase')) {
    return isDemoMode() ? demoUser() : null;
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    // No live session. In DEMO_MODE, bind to the real is_demo employee so the dev loop
    // isn't a magic-link wall and the views key off real data; otherwise unauthenticated.
    return isDemoMode() ? await demoUserFromDb() : null;
  }

  return getEmployeeForUid(user.id, user.email ?? null);
}

/**
 * Resolve a Supabase auth uid → its employee row + roles. Returns null if no
 * employee is linked yet (e.g. a fresh sign-in before provisioning). Demo fallback
 * applies when DEMO_MODE is on and the lookup yields nothing.
 */
export async function getEmployeeForUid(uid: string, email: string | null): Promise<AuthUser | null> {
  if (!isConfigured('supabase')) {
    return isDemoMode() ? demoUser() : null;
  }

  const supabase = await createClient();

  // The generated `Database` placeholder has no Tables yet (regenerated by
  // `npm run db:types`). Until then, query app tables through `appTable()`, a
  // loosely-typed escape hatch, so this resolver type-checks keyless. Once types are
  // generated the queries can be tightened to the typed client.
  const db = appTable(supabase);

  // employees is keyed to auth.users via user_id. RLS lets a user read their own row.
  const { data: employee } = await db
    .from('employees')
    .select('id, function_id, name, email, is_demo')
    .eq('user_id', uid)
    .maybeSingle();

  if (!employee) {
    return isDemoMode() ? await demoUserFromDb() : null;
  }

  const emp = employee as {
    id: string;
    function_id: string;
    name: string;
    email: string | null;
    is_demo: boolean;
  };

  const { data: roleRows } = await db.from('employee_roles').select('role').eq('employee_id', emp.id);

  const roles = (((roleRows ?? []) as { role: AppRole }[]) || []).map((r) => r.role);

  return {
    userId: uid,
    employeeId: emp.id,
    functionId: emp.function_id,
    displayName: emp.name,
    email: emp.email ?? email,
    roles: roles.length > 0 ? roles : ['developer'],
    isDemo: emp.is_demo,
  };
}

/** Like getAuthUser but throws when unauthenticated — for paths that require a user. */
export async function requireAuthUser(): Promise<AuthUser> {
  const user = await getAuthUser();
  if (!user) {
    throw new Error('Unauthorized: no authenticated user.');
  }
  return user;
}
