'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { CourseAssignment, MyRecommendationAction } from '@/lib/actions/store';

type Resource = { readonly title: string; readonly provider: string; readonly url: string; readonly description: string };

function RecommendationReasoning({ evidence }: { evidence: Record<string, unknown> }) {
  const output = evidence.output && typeof evidence.output === 'object' ? evidence.output as Record<string, unknown> : null;
  if (!output) return <div className="action-evidence"><strong>Evidence</strong><code>{Object.keys(evidence).length ? JSON.stringify(evidence) : 'Legacy recommendation without a versioned trace'}</code></div>;
  const rows = [
    ['Action', output.action],
    ['Expected signal', output.expectedSignal],
    ['Verification', output.verificationPlan],
    ['Alternative explanation', output.alternativeExplanation],
    ['Do-no-harm guard', output.doNoHarm],
  ];
  return <details className="recommendation-reasoning" open><summary>Reasoning and verification contract</summary><dl>{rows.map(([label, value]) => <div key={String(label)}><dt>{String(label)}</dt><dd>{String(value ?? 'Not recorded')}</dd></div>)}</dl><code>{JSON.stringify(evidence.evidence ?? evidence)}</code></details>;
}

export function MyActionsClient({ recommendations, assignments, resources }: { recommendations: MyRecommendationAction[]; assignments: CourseAssignment[]; resources: readonly Resource[] }) {
  const router = useRouter(); const [tab, setTab] = useState<'recommendations'|'courses'>('recommendations'); const [working, setWorking] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  async function act(id: string, eventType: 'acknowledged'|'started'|'actioned'|'dismissed') { setWorking(id); setNotice(null); try { const response = await fetch('/api/actions/recommendations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ recommendationId: id, eventType }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? 'Could not update action'); setNotice(eventType === 'actioned' ? 'Action recorded. Prism will verify later evidence before marking adoption or impact.' : 'Recommendation status updated.'); router.refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not update action'); } finally { setWorking(null); } }
  return <div className="subview-shell"><nav className="section-nav" aria-label="My Actions sections"><span className="section-nav-label">My Actions</span><button className={tab === 'recommendations' ? 'active' : ''} onClick={() => setTab('recommendations')}><i /><span><strong>Recommendations</strong><small>Evidence-bound actions</small></span></button><button className={tab === 'courses' ? 'active' : ''} onClick={() => setTab('courses')}><i /><span><strong>Courses</strong><small>Assigned and public learning</small></span></button></nav><div className="subview-stage">{notice ? <div className="action-notice" role="status">{notice}</div> : null}
    {tab === 'recommendations' ? <section className="action-list">{recommendations.length ? recommendations.map((item) => <article key={item.id}><header><span className={`action-kind ${item.kind}`}>{item.kind}</span><span className="action-status">{item.status.replace('_',' ')}</span></header><h2>{item.ref}</h2><p>{item.rationale || 'The deterministic rule emitted this action from the current scoring evidence.'}</p><RecommendationReasoning evidence={item.evidence} />{item.lastAction ? <small>Last human action: {item.lastAction}</small> : null}<footer>{item.status === 'suggested' ? <button className="button" disabled={working === item.id} onClick={() => act(item.id,'acknowledged')}>Acknowledge</button> : null}{!['adopted','dismissed'].includes(item.status) ? <><button className="button" disabled={working === item.id} onClick={() => act(item.id,'started')}>Start</button><button className="button primary" disabled={working === item.id} onClick={() => act(item.id,'actioned')}>{working === item.id ? 'Saving…' : 'I actioned this'}</button><button className="button ghost" disabled={working === item.id} onClick={() => act(item.id,'dismissed')}>Dismiss</button></> : <span className="action-closed">Resolved by evidence or user decision</span>}</footer></article>) : <div className="card action-empty"><strong>No recommendation yet</strong><p>Prism waits for a real scored window and a matching deterministic rule.</p></div>}</section> : <section className="course-resource-section">{assignments.length ? <div className="assigned-learning"><h2>Assigned learning</h2>{assignments.map((course) => <article key={course.id}><span>{course.status.replace('_',' ')}</span><strong>{course.title}</strong><p>{course.progressPct}% recorded progress{course.dueAt ? ` · due ${new Date(course.dueAt).toLocaleDateString()}` : ''}</p>{course.url ? <a className="button" href={course.url} target="_blank" rel="noreferrer">Open assignment</a> : <small>Course URL is not available from the learning provider.</small>}</article>)}</div> : null}<div className="resource-grid"><div className="section-heading"><div><span className="page-kicker">Official public learning</span><h2>Explore without a fabricated assignment</h2></div></div>{resources.map((resource) => <a href={resource.url} target="_blank" rel="noreferrer" key={resource.url}><span>{resource.provider}</span><strong>{resource.title}</strong><p>{resource.description}</p><b>Open official resource →</b></a>)}</div></section>}
  </div></div>;
}
