'use client';

import { useState } from 'react'; import { useRouter } from 'next/navigation'; import type { OrgActionCandidate, OrgActionRow } from '@/lib/actions/store';

export function OrgActionsClient({ actions, candidates }: { actions: OrgActionRow[]; candidates: OrgActionCandidate[] }) {
  const router = useRouter(); const [working, setWorking] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  async function request(payload: Record<string, unknown>, key: string) { setWorking(key); setNotice(null); try { const response = await fetch('/api/actions/org', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? 'Could not update action'); setNotice('Organization action updated. Prism has not claimed impact; verify it against later evidence.'); router.refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not update action'); } finally { setWorking(null); } }
  return <>{notice ? <div className="action-notice" role="status">{notice}</div> : null}<section className="org-candidates"><div className="section-heading"><div><span className="page-kicker">Suggested from current evidence</span><h2>Opportunities ready to plan</h2></div></div>{candidates.length ? <div className="candidate-grid">{candidates.map((candidate, index) => <article key={`${candidate.title}-${index}`}><span>{candidate.kind}</span><h3>{candidate.title}</h3><p>{candidate.rationale}</p><code>{JSON.stringify(candidate.evidence)}</code><button className="button primary" disabled={working !== null} onClick={() => request({ operation: 'create', ...candidate }, `candidate-${index}`)}>{working === `candidate-${index}` ? 'Creating…' : 'Create owned action'}</button></article>)}</div> : <div className="card action-empty"><strong>No new candidate</strong><p>Prism found no current connector gap, open course follow-up, or real improvement insight.</p></div>}</section><section className="org-action-board"><div className="section-heading"><div><span className="page-kicker">Accountability board</span><h2>Planned and active work</h2></div></div>{actions.length ? actions.map((action) => <article key={action.id}><div><span className={`action-kind ${action.kind}`}>{action.kind}</span><strong>{action.title}</strong><p>{action.rationale}</p></div><div className="org-action-meta"><span>Owner: {action.ownerName ?? 'Unassigned'}</span><span>Scope: {action.teamName ?? 'Organization'}</span><span>Due: {action.dueAt ? new Date(action.dueAt).toLocaleDateString() : 'Not set'}</span></div><select value={action.status} disabled={working === action.id} onChange={(event) => request({ operation: 'update', id: action.id, status: event.target.value }, action.id)}><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="actioned">Actioned · awaiting evidence</option><option value="verified">Verified by follow-up</option><option value="dismissed">Dismissed</option></select><code>{Object.keys(action.evidence).length ? JSON.stringify(action.evidence) : 'No structured evidence attached'}</code></article>) : <div className="card action-empty"><strong>No organization action created</strong><p>Use a real evidence-backed candidate above to start the board.</p></div>}</section></>;
}
