'use client';

// Agent artifacts in the v1 design system:
//   good  → .well/.wellitem (the v1 "what's going well" treatment)
//   bad   → .ins/.insitem
//   Generate/Refresh button → .linkbtn, POSTs /api/v3/agent, then refreshes.
// The chip states the provenance honestly: which model, grounded, from YOUR data.

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { AgentArtifactRow } from '@prism/contract';

export function AgentRunButton({ developerId, hasArtifacts }: { developerId: string; hasArtifacts: boolean }) {
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();

  const run = async () => {
    setRunning(true);
    setError(null);
    try {
      const res = await fetch('/api/v3/agent', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ developerId }),
      });
      if (!res.ok) throw new Error((await res.json()).error ?? 'agent run failed');
      router.refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'agent run failed');
    } finally {
      setRunning(false);
    }
  };

  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
      <button type="button" className="linkbtn" disabled={running} onClick={run}
        style={{ borderColor: 'var(--prof)', color: running ? 'var(--mut)' : 'var(--ink)' }}>
        {running ? 'agent analyzing your data…' : hasArtifacts ? '↻ Re-run coaching agent' : '✦ Run coaching agent'}
      </button>
      {error ? <span className="stchip st-prog">{error}</span> : null}
    </span>
  );
}

const CAT_CLASS: Record<string, string> = {
  skill: 'skill', verification: 'qual', prompt: 'prompt', context: 'waste', process: 'qual',
};
const CAT_GLYPH: Record<string, string> = {
  skill: 'S', verification: 'V', prompt: 'P', context: 'C', process: '⚙',
};

export function AgentGoodBad({ artifacts, developerId }: { artifacts: AgentArtifactRow[]; developerId: string }) {
  const good = artifacts.filter((a) => a.kind === 'good');
  const bad = artifacts.filter((a) => a.kind === 'bad');
  const model = artifacts[0]?.model;

  return (
    <div className="card">
      <div className="cardhead">
        <h3>Coaching agent — your read</h3>
        <span className="sub">
          {model ? `generated by ${model} · grounded (numbers verified against your data)` : 'not generated yet'}
        </span>
      </div>
      <div className="daterow" style={{ marginBottom: good.length + bad.length ? 14 : 0 }}>
        <AgentRunButton developerId={developerId} hasArtifacts={good.length + bad.length > 0} />
        <span className="pill">reads: your KPIs · findings · coaching outcomes · adoptions</span>
      </div>
      {good.length + bad.length === 0 ? (
        <p className="muted" style={{ fontSize: 12.5 }}>
          Run the agent to get a personal read: what&apos;s going well, what needs attention,
          course picks and concrete practice suggestions — all grounded in your own numbers.
        </p>
      ) : (
        <div className="row r2" style={{ marginBottom: 0 }}>
          <div>
            <div className="cardhead" style={{ marginBottom: 10 }}>
              <h3 style={{ fontSize: 13, color: 'var(--good)' }}>What&apos;s going well</h3>
            </div>
            <div className="well">
              {good.map((a) => (
                <div className="wellitem" key={a.id}>
                  <span className="cat waste">✓</span>
                  <span className="tx">
                    <b>{a.title}</b>
                    <span className="cause">{a.body} {a.targets.length ? <em>{a.targets.join(' · ')}</em> : null}</span>
                  </span>
                </div>
              ))}
            </div>
          </div>
          <div>
            <div className="cardhead" style={{ marginBottom: 10 }}>
              <h3 style={{ fontSize: 13, color: 'var(--warn)' }}>What needs attention</h3>
            </div>
            <div className="ins">
              {bad.map((a) => (
                <div className="insitem" key={a.id}>
                  <span className="n">!</span>
                  <span className="tx">
                    <b>{a.title}</b>
                    <small>{a.body}</small>
                  </span>
                  {a.targets.length ? <span className="tag2 effness">{a.targets.join(' · ')}</span> : null}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export function AgentSuggestions({
  artifacts, onAdopt, adopted, pending,
}: {
  artifacts: AgentArtifactRow[];
  onAdopt: (ref: string, label: string) => void;
  adopted: (ref: string) => boolean;
  pending: (ref: string) => boolean;
}) {
  const suggestions = artifacts.filter((a) => a.kind === 'suggestion');
  if (!suggestions.length) return null;
  return (
    <div className="card">
      <div className="cardhead">
        <h3>Agent suggestions — practice changes</h3>
        <span className="sub">generated by {suggestions[0]!.model} · grounded · adopt = tracked in user_context</span>
      </div>
      <div className="well">
        {suggestions.map((a) => {
          const ref = `agent-suggestion:${a.title}`;
          const done = adopted(ref);
          return (
            <div className="wellitem" key={a.id}>
              <span className={`cat ${CAT_CLASS[a.category ?? 'process']}`}>{CAT_GLYPH[a.category ?? 'process']}</span>
              <span className="tx">
                <b>{a.title}</b>
                <span className="cause">
                  {a.body} {a.ref ? <em>ref: {a.ref}</em> : null}{' '}
                  {a.targets.length ? <em>lifts: {a.targets.join(', ')}</em> : null}
                </span>
                <button
                  type="button" className="linkbtn"
                  style={{ marginTop: 8, ...(done ? { color: 'var(--good)', borderColor: 'var(--good)' } : {}) }}
                  disabled={pending(ref)}
                  onClick={() => onAdopt(ref, a.title)}
                >
                  {done ? '✓ adopted — tracked' : 'I adopted this'}
                </button>
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export function AgentCoursePicks({ artifacts }: { artifacts: AgentArtifactRow[] }) {
  const picks = artifacts.filter((a) => a.kind === 'course');
  if (!picks.length) return null;
  return (
    <div className="ins" style={{ marginBottom: 14 }}>
      {picks.map((a) => (
        <div className="insitem" key={a.id}>
          <span className="n">★</span>
          <span className="tx">
            <b>Coach&apos;s pick: {a.title}</b>
            <small>{a.body}</small>
          </span>
          <span className="tag2 prof">{String((a.meta as { minutes?: number }).minutes ?? '—')} min</span>
        </div>
      ))}
    </div>
  );
}
