// components/panels/CourseCard.tsx
//
// The assigned-course card (My view). Faithful port of the design's `.course` anchor:
// a link that opens the agentic-learning-studio course site in a new tab, with the
// `.ico` mortarboard glyph, title + blurb, a `.cprog` progress bar at `progressPct`,
// and the `.opencourse` affordance. When no course is assigned yet (course === null)
// it renders a disabled awaiting-signal variant — no fabricated course, no dead link.
//
// Server Component (read-only).

import type { CourseDTO } from '@/lib/ui/view-models';

/** The mortarboard `.ico` SVG from the approved design. */
function CourseGlyph() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path d="M3 7l9-4 9 4-9 4-9-4z" stroke="#a78bfa" strokeWidth="1.6" />
      <path d="M7 9.5V15c0 1 2.2 2.5 5 2.5s5-1.5 5-2.5V9.5" stroke="#a78bfa" strokeWidth="1.6" />
    </svg>
  );
}

export interface CourseCardProps {
  course: CourseDTO | null;
}

export function CourseCard({ course }: CourseCardProps) {
  // Awaiting state: no course assigned yet. Same `.course` shell, but it is a
  // non-interactive <div> (not a link), the progress bar reads 0, and the affordance
  // is disabled. The studio assigns a course from the weakest dimension once scored.
  if (!course) {
    return (
      <div
        className="course"
        aria-disabled
        style={{ textDecoration: 'none', color: 'inherit', opacity: 0.72, cursor: 'default' }}
      >
        <div className="ico">
          <CourseGlyph />
        </div>
        <div className="meta">
          <b>No course assigned yet</b>
          <p>
            The agentic learning studio assigns a micro-course from your weakest dimension once
            you have a scored window — it will appear here, ready to open.
          </p>
        </div>
        <div className="cprog">
          <div className="bar">
            <i style={{ width: '0%' }} />
          </div>
          <small>awaiting your first scored window</small>
        </div>
        <span className="opencourse" style={{ opacity: 0.5 }}>
          Open course →
        </span>
      </div>
    );
  }

  const pct = Math.max(0, Math.min(100, Math.round(course.progressPct)));

  return (
    <a
      className="course"
      href={course.url}
      target="_blank"
      rel="noopener noreferrer"
      style={{ textDecoration: 'none', color: 'inherit' }}
    >
      <div className="ico">
        <CourseGlyph />
      </div>
      <div className="meta">
        <b>Assigned: {course.title}</b>
        <p>
          Pre-generated by the agentic learning studio · opens in the course site · completion is
          marked when you pass the knowledge check.
        </p>
      </div>
      <div className="cprog">
        <div className="bar">
          <i style={{ width: `${pct}%` }} />
        </div>
        <small>{course.statusLabel}</small>
      </div>
      <span className="opencourse">Open course →</span>
    </a>
  );
}
